version: "3"
services:
  db:
    image: postgres:16.1
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: crud
      POSTGRES_USER: thinline20
      POSTGRES_PASSWORD: thisis3ysuperlife
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
